# Generated by Django 2.1.1 on 2018-10-25 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Client Name', max_length=100, verbose_name='Name')),
                ('cpf', models.CharField(help_text='Client CPF', max_length=15, verbose_name='CPF')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField(verbose_name='Order total price')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Product Name', max_length=100, verbose_name='Name')),
                ('category', models.CharField(help_text='Product Category', max_length=50, verbose_name='Category')),
                ('price', models.FloatField(verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Store Name', max_length=100, verbose_name='Name')),
                ('category', models.CharField(help_text='Store Category', max_length=50, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Store'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='products',
            field=models.ManyToManyField(to='api.Product'),
        ),
    ]
